// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MdmServiceClient is the client API for MdmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MdmServiceClient interface {
	// StartLocalDevice starts a Mobile Device on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the mdm/config.yaml
	//   3. all bytes constituting the Device YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalDevice(ctx context.Context, opts ...grpc.CallOption) (MdmService_StartLocalDeviceClient, error)
	// StartFromPreviousDevice starts a new Mobile Device based on a previous one.
	// If the previous Mobile Device does not have the can-replay condition set this call will result in an error.
	StartFromPreviousDevice(ctx context.Context, in *StartFromPreviousDeviceRequest, opts ...grpc.CallOption) (*StartDeviceResponse, error)
	// StartDeviceRequest starts a new Mobile Device based on its specification.
	StartDevice(ctx context.Context, in *StartDeviceRequest, opts ...grpc.CallOption) (*StartDeviceResponse, error)
	// Searches for Mobile Device(s) known to this instance
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// Subscribe listens to new Mobile Device(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MdmService_SubscribeClient, error)
	// GetDevice retrieves details of a single Mobile Device
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	// Listen listens to Mobile Device updates and log output of a running Mobile Device
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (MdmService_ListenClient, error)
	// StopDevice stops a currently running Mobile Device
	StopDevice(ctx context.Context, in *StopDeviceRequest, opts ...grpc.CallOption) (*StopDeviceResponse, error)
}

type mdmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMdmServiceClient(cc grpc.ClientConnInterface) MdmServiceClient {
	return &mdmServiceClient{cc}
}

func (c *mdmServiceClient) StartLocalDevice(ctx context.Context, opts ...grpc.CallOption) (MdmService_StartLocalDeviceClient, error) {
	stream, err := c.cc.NewStream(ctx, &MdmService_ServiceDesc.Streams[0], "/v1.MdmService/StartLocalDevice", opts...)
	if err != nil {
		return nil, err
	}
	x := &mdmServiceStartLocalDeviceClient{stream}
	return x, nil
}

type MdmService_StartLocalDeviceClient interface {
	Send(*StartLocalDeviceRequest) error
	CloseAndRecv() (*StartDeviceResponse, error)
	grpc.ClientStream
}

type mdmServiceStartLocalDeviceClient struct {
	grpc.ClientStream
}

func (x *mdmServiceStartLocalDeviceClient) Send(m *StartLocalDeviceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mdmServiceStartLocalDeviceClient) CloseAndRecv() (*StartDeviceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartDeviceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mdmServiceClient) StartFromPreviousDevice(ctx context.Context, in *StartFromPreviousDeviceRequest, opts ...grpc.CallOption) (*StartDeviceResponse, error) {
	out := new(StartDeviceResponse)
	err := c.cc.Invoke(ctx, "/v1.MdmService/StartFromPreviousDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) StartDevice(ctx context.Context, in *StartDeviceRequest, opts ...grpc.CallOption) (*StartDeviceResponse, error) {
	out := new(StartDeviceResponse)
	err := c.cc.Invoke(ctx, "/v1.MdmService/StartDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, "/v1.MdmService/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MdmService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &MdmService_ServiceDesc.Streams[1], "/v1.MdmService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &mdmServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MdmService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type mdmServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *mdmServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mdmServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, "/v1.MdmService/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (MdmService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &MdmService_ServiceDesc.Streams[2], "/v1.MdmService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &mdmServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MdmService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type mdmServiceListenClient struct {
	grpc.ClientStream
}

func (x *mdmServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mdmServiceClient) StopDevice(ctx context.Context, in *StopDeviceRequest, opts ...grpc.CallOption) (*StopDeviceResponse, error) {
	out := new(StopDeviceResponse)
	err := c.cc.Invoke(ctx, "/v1.MdmService/StopDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MdmServiceServer is the server API for MdmService service.
// All implementations must embed UnimplementedMdmServiceServer
// for forward compatibility
type MdmServiceServer interface {
	// StartLocalDevice starts a Mobile Device on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the mdm/config.yaml
	//   3. all bytes constituting the Device YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalDevice(MdmService_StartLocalDeviceServer) error
	// StartFromPreviousDevice starts a new Mobile Device based on a previous one.
	// If the previous Mobile Device does not have the can-replay condition set this call will result in an error.
	StartFromPreviousDevice(context.Context, *StartFromPreviousDeviceRequest) (*StartDeviceResponse, error)
	// StartDeviceRequest starts a new Mobile Device based on its specification.
	StartDevice(context.Context, *StartDeviceRequest) (*StartDeviceResponse, error)
	// Searches for Mobile Device(s) known to this instance
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// Subscribe listens to new Mobile Device(s) updates
	Subscribe(*SubscribeRequest, MdmService_SubscribeServer) error
	// GetDevice retrieves details of a single Mobile Device
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	// Listen listens to Mobile Device updates and log output of a running Mobile Device
	Listen(*ListenRequest, MdmService_ListenServer) error
	// StopDevice stops a currently running Mobile Device
	StopDevice(context.Context, *StopDeviceRequest) (*StopDeviceResponse, error)
	mustEmbedUnimplementedMdmServiceServer()
}

// UnimplementedMdmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMdmServiceServer struct {
}

func (UnimplementedMdmServiceServer) StartLocalDevice(MdmService_StartLocalDeviceServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalDevice not implemented")
}
func (UnimplementedMdmServiceServer) StartFromPreviousDevice(context.Context, *StartFromPreviousDeviceRequest) (*StartDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousDevice not implemented")
}
func (UnimplementedMdmServiceServer) StartDevice(context.Context, *StartDeviceRequest) (*StartDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDevice not implemented")
}
func (UnimplementedMdmServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedMdmServiceServer) Subscribe(*SubscribeRequest, MdmService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedMdmServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedMdmServiceServer) Listen(*ListenRequest, MdmService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedMdmServiceServer) StopDevice(context.Context, *StopDeviceRequest) (*StopDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopDevice not implemented")
}
func (UnimplementedMdmServiceServer) mustEmbedUnimplementedMdmServiceServer() {}

// UnsafeMdmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MdmServiceServer will
// result in compilation errors.
type UnsafeMdmServiceServer interface {
	mustEmbedUnimplementedMdmServiceServer()
}

func RegisterMdmServiceServer(s grpc.ServiceRegistrar, srv MdmServiceServer) {
	s.RegisterService(&MdmService_ServiceDesc, srv)
}

func _MdmService_StartLocalDevice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MdmServiceServer).StartLocalDevice(&mdmServiceStartLocalDeviceServer{stream})
}

type MdmService_StartLocalDeviceServer interface {
	SendAndClose(*StartDeviceResponse) error
	Recv() (*StartLocalDeviceRequest, error)
	grpc.ServerStream
}

type mdmServiceStartLocalDeviceServer struct {
	grpc.ServerStream
}

func (x *mdmServiceStartLocalDeviceServer) SendAndClose(m *StartDeviceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mdmServiceStartLocalDeviceServer) Recv() (*StartLocalDeviceRequest, error) {
	m := new(StartLocalDeviceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MdmService_StartFromPreviousDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).StartFromPreviousDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MdmService/StartFromPreviousDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).StartFromPreviousDevice(ctx, req.(*StartFromPreviousDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_StartDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).StartDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MdmService/StartDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).StartDevice(ctx, req.(*StartDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MdmService/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MdmServiceServer).Subscribe(m, &mdmServiceSubscribeServer{stream})
}

type MdmService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type mdmServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *mdmServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MdmService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MdmService/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MdmServiceServer).Listen(m, &mdmServiceListenServer{stream})
}

type MdmService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type mdmServiceListenServer struct {
	grpc.ServerStream
}

func (x *mdmServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MdmService_StopDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).StopDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MdmService/StopDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).StopDevice(ctx, req.(*StopDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MdmService_ServiceDesc is the grpc.ServiceDesc for MdmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MdmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MdmService",
	HandlerType: (*MdmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousDevice",
			Handler:    _MdmService_StartFromPreviousDevice_Handler,
		},
		{
			MethodName: "StartDevice",
			Handler:    _MdmService_StartDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _MdmService_ListDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _MdmService_GetDevice_Handler,
		},
		{
			MethodName: "StopDevice",
			Handler:    _MdmService_StopDevice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalDevice",
			Handler:       _MdmService_StartLocalDevice_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _MdmService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _MdmService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mdm.proto",
}
